# Generated by Django 6.0.2 on 2026-02-19 21:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Productor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(max_length=200)),
                ('codigo', models.CharField(max_length=40, unique=True)),
                ('telefono', models.CharField(blank=True, max_length=30)),
                ('activo', models.BooleanField(default=True)),
                ('notas', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='TipoCambio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fecha', models.DateField(unique=True)),
                ('valor', models.DecimalField(decimal_places=4, max_digits=12)),
                ('fuente', models.CharField(default='Diario Oficial de la Federacion', max_length=120)),
            ],
            options={
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='Anticipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fecha', models.DateField()),
                ('monto_mxn', models.DecimalField(decimal_places=2, max_digits=14)),
                ('referencia', models.CharField(blank=True, max_length=80)),
                ('notas', models.TextField(blank=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('aplicado', 'Aplicado')], default='pendiente', max_length=20)),
                ('productor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='anticipos', to='pagos.productor')),
            ],
            options={
                'ordering': ['-fecha', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fecha', models.DateField()),
                ('folio', models.CharField(max_length=40, unique=True)),
                ('kilos', models.DecimalField(decimal_places=2, max_digits=12)),
                ('precio_kg_mxn', models.DecimalField(decimal_places=4, max_digits=12)),
                ('notas', models.TextField(blank=True)),
                ('productor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='compras', to='pagos.productor')),
                ('tipo_cambio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='compras', to='pagos.tipocambio')),
            ],
            options={
                'ordering': ['-fecha', '-id'],
            },
        ),
        migrations.CreateModel(
            name='AplicacionAnticipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fecha', models.DateField()),
                ('monto_aplicado_mxn', models.DecimalField(decimal_places=2, max_digits=14)),
                ('anticipo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='aplicaciones', to='pagos.anticipo')),
                ('compra', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='aplicaciones_anticipo', to='pagos.compra')),
            ],
            options={
                'ordering': ['-fecha', '-id'],
                'constraints': [models.UniqueConstraint(fields=('anticipo', 'compra', 'fecha'), name='unique_aplicacion_anticipo_compra_fecha')],
            },
        ),
    ]
