# Generated by Django 6.0.2 on 2026-02-19 21:33

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='anticipo',
            options={'ordering': ['-fecha_pago', '-numero_anticipo']},
        ),
        migrations.AlterModelOptions(
            name='compra',
            options={'ordering': ['-fecha_liq', '-id']},
        ),
        migrations.RemoveField(
            model_name='anticipo',
            name='fecha',
        ),
        migrations.RemoveField(
            model_name='anticipo',
            name='monto_mxn',
        ),
        migrations.RemoveField(
            model_name='anticipo',
            name='notas',
        ),
        migrations.RemoveField(
            model_name='anticipo',
            name='referencia',
        ),
        migrations.RemoveField(
            model_name='aplicacionanticipo',
            name='monto_aplicado_mxn',
        ),
        migrations.RemoveField(
            model_name='compra',
            name='fecha',
        ),
        migrations.RemoveField(
            model_name='compra',
            name='folio',
        ),
        migrations.RemoveField(
            model_name='compra',
            name='kilos',
        ),
        migrations.RemoveField(
            model_name='compra',
            name='notas',
        ),
        migrations.RemoveField(
            model_name='compra',
            name='precio_kg_mxn',
        ),
        migrations.RemoveField(
            model_name='tipocambio',
            name='valor',
        ),
        migrations.AddField(
            model_name='anticipo',
            name='contador',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='anticipo',
            name='correo_para_facturas',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='anticipo',
            name='cuenta',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='anticipo',
            name='cuenta_de_pago',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='anticipo',
            name='factura',
            field=models.CharField(blank=True, help_text='UUID factura', max_length=80),
        ),
        migrations.AddField(
            model_name='anticipo',
            name='fecha_pago',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
        migrations.AddField(
            model_name='anticipo',
            name='moneda',
            field=models.CharField(choices=[('PESOS', 'Pesos'), ('DOLARES', 'Dolares'), ('PESOS/DOLARES', 'Pesos/Dolares')], default='DOLARES', max_length=20),
        ),
        migrations.AddField(
            model_name='anticipo',
            name='monto_anticipo',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=16),
        ),
        migrations.AddField(
            model_name='anticipo',
            name='numero_anticipo',
            field=models.PositiveIntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='anticipo',
            name='observaciones',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='anticipo',
            name='pendiente_aplicar',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('APLICADO', 'Aplicado')], default='PENDIENTE', max_length=20),
        ),
        migrations.AddField(
            model_name='anticipo',
            name='persona_que_factura',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='anticipo',
            name='telefono',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='anticipo',
            name='total_en_pesos',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=16, null=True),
        ),
        migrations.AddField(
            model_name='anticipo',
            name='uuid_nota_credito',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='aplicacionanticipo',
            name='monto_aplicado',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=16),
        ),
        migrations.AddField(
            model_name='compra',
            name='anticipo',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=16),
        ),
        migrations.AddField(
            model_name='compra',
            name='compra_en_libras',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=16, null=True),
        ),
        migrations.AddField(
            model_name='compra',
            name='contador',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='compra',
            name='correo',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='compra',
            name='cuenta_de_pago',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='compra',
            name='cuenta_productor',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='compra',
            name='dias_transcurridos',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='compra',
            name='estatus_de_pago',
            field=models.CharField(choices=[('PAGADO', 'Pagado'), ('PENDIENTE', 'Pendiente'), ('PARCIAL', 'Parcial')], default='PENDIENTE', max_length=20),
        ),
        migrations.AddField(
            model_name='compra',
            name='estatus_factura',
            field=models.CharField(choices=[('FACTURADO', 'Facturado'), ('PENDIENTE', 'Pendiente')], default='FACTURADO', max_length=20),
        ),
        migrations.AddField(
            model_name='compra',
            name='estatus_rep',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='compra',
            name='factura',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='compra',
            name='fecha_de_pago',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
        migrations.AddField(
            model_name='compra',
            name='fecha_liq',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
        migrations.AddField(
            model_name='compra',
            name='intereses',
            field=models.CharField(choices=[('SI', 'Si'), ('NO', 'No')], default='NO', max_length=2),
        ),
        migrations.AddField(
            model_name='compra',
            name='metodo_de_pago',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name='compra',
            name='moneda',
            field=models.CharField(choices=[('PESOS', 'Pesos'), ('DOLARES', 'Dolares'), ('PESOS/DOLARES', 'Pesos/Dolares')], default='DOLARES', max_length=20),
        ),
        migrations.AddField(
            model_name='compra',
            name='numero_compra',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='compra',
            name='pacas',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='compra',
            name='pago',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=16, null=True),
        ),
        migrations.AddField(
            model_name='compra',
            name='regimen_fiscal',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='compra',
            name='retencion_deudas_mxn',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=16),
        ),
        migrations.AddField(
            model_name='compra',
            name='retencion_deudas_usd',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=16),
        ),
        migrations.AddField(
            model_name='compra',
            name='retencion_resico',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=16),
        ),
        migrations.AddField(
            model_name='compra',
            name='saldo_pendiente',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=16),
        ),
        migrations.AddField(
            model_name='compra',
            name='tipo_cambio_valor',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='compra',
            name='total_deuda_en_dls',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=16),
        ),
        migrations.AddField(
            model_name='compra',
            name='total_en_pesos',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=16),
        ),
        migrations.AddField(
            model_name='compra',
            name='uuid_factura',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='compra',
            name='uuid_ppd',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='compra',
            name='vencimiento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productor',
            name='correo_facturas',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='productor',
            name='cuenta_productor',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='productor',
            name='regimen_fiscal',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='tipocambio',
            name='tc',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='anticipo',
            name='estado',
            field=models.CharField(choices=[('FACTURADO', 'Facturado'), ('PENDIENTE', 'Pendiente')], default='FACTURADO', max_length=20),
        ),
        migrations.AlterField(
            model_name='compra',
            name='tipo_cambio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='compras', to='pagos.tipocambio'),
        ),
    ]
