# Generated by Django 6.0.2 on 2026-02-19 22:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0002_alter_anticipo_options_alter_compra_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='compra',
            name='expediente_completo',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='compra',
            name='fecha_solicitud_factura',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='compra',
            name='solicitud_factura_enviada',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='DocumentoCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('etapa', models.CharField(choices=[('solicitud_factura', 'Solicitud Factura'), ('factura', 'Factura'), ('pago', 'Pago'), ('otro', 'Otro')], default='otro', max_length=30)),
                ('descripcion', models.CharField(blank=True, max_length=200)),
                ('archivo', models.FileField(upload_to='compras_documentos/%Y/%m/')),
                ('compra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='pagos.compra')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
    ]
