# Generated by Django 6.0.2 on 2026-02-20 00:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0003_compra_expediente_completo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='compra',
            name='anticipos_revisados',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='compra',
            name='deudas_revisadas',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='compra',
            name='division_revisada',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='compra',
            name='parent_compra',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='divisiones', to='pagos.compra'),
        ),
        migrations.AddField(
            model_name='compra',
            name='porcentaje_division',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
    ]
