# Generated by Django 6.0.2 on 2026-02-23 15:34

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0004_compra_anticipos_revisados_compra_deudas_revisadas_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PagoCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fecha_pago', models.DateField(default=django.utils.timezone.localdate)),
                ('monto', models.DecimalField(decimal_places=4, max_digits=16)),
                ('moneda', models.CharField(choices=[('PESOS', 'Pesos'), ('DOLARES', 'Dolares'), ('PESOS/DOLARES', 'Pesos/Dolares')], default='DOLARES', max_length=20)),
                ('cuenta_de_pago', models.CharField(blank=True, max_length=120)),
                ('metodo_de_pago', models.CharField(blank=True, max_length=60)),
                ('referencia', models.CharField(blank=True, max_length=100)),
                ('notas', models.TextField(blank=True)),
                ('compra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos_registrados', to='pagos.compra')),
            ],
            options={
                'ordering': ['-fecha_pago', '-id'],
            },
        ),
    ]
