# Generated by Django 6.0.2 on 2026-03-09 15:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0005_pagocompra'),
    ]

    operations = [
        migrations.AddField(
            model_name='compra',
            name='workflow_state',
            field=models.CharField(choices=[('IMPORTED', 'Imported'), ('DEBT_CALCULATED', 'Debt Calculated'), ('WAITING_INVOICE', 'Waiting Invoice'), ('INVOICE_RECEIVED', 'Invoice Received'), ('INVOICE_VALID', 'Invoice Valid'), ('INVOICE_BLOCKED', 'Invoice Blocked'), ('WAITING_BANK_CONFIRMATION', 'Waiting Bank Confirmation'), ('READY_TO_PAY', 'Ready To Pay'), ('PAID', 'Paid'), ('ARCHIVED', 'Archived')], db_index=True, default='IMPORTED', max_length=40),
        ),
        migrations.CreateModel(
            name='DebtSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fuente', models.CharField(default='microsip', max_length=60)),
                ('total_usd', models.DecimalField(decimal_places=4, default=0, max_digits=16)),
                ('total_mxn', models.DecimalField(decimal_places=4, default=0, max_digits=16)),
                ('detalle_json', models.JSONField(blank=True, default=dict)),
                ('compra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='debt_snapshots', to='pagos.compra')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Deduccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('concepto', models.CharField(max_length=120)),
                ('monto', models.DecimalField(decimal_places=4, max_digits=16)),
                ('moneda', models.CharField(choices=[('PESOS', 'Pesos'), ('DOLARES', 'Dolares'), ('PESOS/DOLARES', 'Pesos/Dolares')], default='DOLARES', max_length=20)),
                ('fuente', models.CharField(default='manual', max_length=30)),
                ('notas', models.TextField(blank=True)),
                ('compra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deducciones', to='pagos.compra')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='WorkflowEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('from_state', models.CharField(blank=True, max_length=40)),
                ('to_state', models.CharField(max_length=40)),
                ('actor', models.CharField(default='system', max_length=120)),
                ('reason', models.TextField(blank=True)),
                ('compra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workflow_events', to='pagos.compra')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
    ]
