# Generated by Django 6.0.2 on 2026-03-09 20:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0006_compra_workflow_state_debtsnapshot_deduccion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvoiceValidationResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.CharField(blank=True, max_length=80)),
                ('rfc_emisor', models.CharField(blank=True, max_length=20)),
                ('rfc_receptor', models.CharField(blank=True, max_length=20)),
                ('uso_cfdi', models.CharField(blank=True, max_length=20)),
                ('metodo_pago', models.CharField(blank=True, max_length=20)),
                ('moneda', models.CharField(blank=True, max_length=20)),
                ('iva_tasa', models.CharField(blank=True, max_length=20)),
                ('isr_retencion', models.DecimalField(decimal_places=6, default=0, max_digits=12)),
                ('valid', models.BooleanField(default=False)),
                ('blocked_reason', models.TextField(blank=True)),
                ('raw_result', models.JSONField(blank=True, default=dict)),
                ('compra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoice_validations', to='pagos.compra')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
    ]
