# Generated by Django 6.0.2 on 2026-03-09 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0007_invoicevalidationresult'),
    ]

    operations = [
        migrations.AddField(
            model_name='compra',
            name='bank_account_confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='compra',
            name='bank_confirmation_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='compra',
            name='bank_confirmation_source',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='compra',
            name='bank_confirmed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
