# Generated by Django 6.0.2 on 2026-03-09 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0008_compra_bank_account_confirmed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productor',
            name='regimen_fiscal_codigo',
            field=models.CharField(blank=True, db_index=True, max_length=3),
        ),
    ]
