# Generated by Django 6.0.2 on 2026-03-09 23:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0009_productor_regimen_fiscal_codigo'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_name', models.CharField(max_length=255)),
                ('dry_run', models.BooleanField(default=False)),
                ('created_count', models.IntegerField(default=0)),
                ('duplicate_count', models.IntegerField(default=0)),
                ('division_count', models.IntegerField(default=0)),
                ('error_count', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ImportRowLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('row_number', models.IntegerField()),
                ('status', models.CharField(default='ok', max_length=20)),
                ('message', models.TextField(blank=True)),
                ('compra_numero', models.IntegerField(blank=True, null=True)),
                ('productor_nombre', models.CharField(blank=True, max_length=200)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rows', to='pagos.importrun')),
            ],
            options={
                'ordering': ['row_number', 'id'],
            },
        ),
    ]
