# Generated by Django 6.0.2 on 2026-03-10 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0011_personafactura_anticipo_persona_facturadora'),
    ]

    operations = [
        migrations.AddField(
            model_name='compra',
            name='cancelada',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='compra',
            name='motivo_cancelacion',
            field=models.TextField(blank=True),
        ),
    ]
