# Generated by Django 6.0.2 on 2026-03-10 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0013_seed_role_groups'),
    ]

    operations = [
        migrations.AddField(
            model_name='productor',
            name='microsip_cliente_id',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='productor',
            name='microsip_cliente_nombre',
            field=models.CharField(blank=True, max_length=240),
        ),
    ]
