# Generated by Django 6.0.2 on 2026-03-11 00:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0014_productor_microsip_cliente_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(max_length=200)),
                ('telefono', models.CharField(blank=True, max_length=40)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.AddField(
            model_name='compra',
            name='facturador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='compras_facturadas', to='pagos.personafactura'),
        ),
        migrations.AddField(
            model_name='personafactura',
            name='regimen_fiscal',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='personafactura',
            name='regimen_fiscal_codigo',
            field=models.CharField(blank=True, db_index=True, max_length=3),
        ),
        migrations.AddField(
            model_name='personafactura',
            name='rfc',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='productor',
            name='contador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='productores', to='pagos.contador'),
        ),
    ]
