# Generated by Django 6.0.2 on 2026-03-11 15:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0015_contador_compra_facturador_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='personafactura',
            name='contador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entidades_facturadoras', to='pagos.contador'),
        ),
    ]
