# Generated by Django 6.0.2 on 2026-03-11 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0016_personafactura_contador'),
    ]

    operations = [
        migrations.AddField(
            model_name='personafactura',
            name='resico_policy',
            field=models.CharField(choices=[('AUTO', 'Auto (retención 1.25% o leyenda)'), ('RETENCION_125', 'Requiere retención ISR 1.25%'), ('EXENCION_LEYENDA', 'Requiere leyenda de exención')], default='AUTO', max_length=30),
        ),
    ]
