# Generated by Django 6.0.2 on 2026-03-11 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0017_personafactura_resico_policy'),
    ]

    operations = [
        migrations.AddField(
            model_name='compra',
            name='expected_forma_pago',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AddField(
            model_name='compra',
            name='expected_metodo_pago',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AddField(
            model_name='compra',
            name='expected_rfc_receptor',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='compra',
            name='expected_uso_cfdi',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
    ]
