# Generated by Django 6.0.2 on 2026-03-11 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0018_compra_expected_forma_pago_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='compra',
            name='expected_moneda',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
    ]
