# Generated by Django 6.0.2 on 2026-03-11 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0019_compra_expected_moneda'),
    ]

    operations = [
        migrations.CreateModel(
            name='XmlValidationConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('key', models.CharField(default='default', max_length=32, unique=True)),
                ('global_rfc_receptor', models.CharField(blank=True, default='', max_length=20)),
            ],
            options={
                'verbose_name': 'Configuración validación XML',
                'verbose_name_plural': 'Configuración validación XML',
            },
        ),
    ]
