# Generated by Django 6.0.2 on 2026-03-11 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0020_xmlvalidationconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='xmlvalidationconfig',
            name='global_codigo_fiscal_receptor',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AddField(
            model_name='xmlvalidationconfig',
            name='global_efecto_comprobante',
            field=models.CharField(blank=True, default='', max_length=4),
        ),
        migrations.AddField(
            model_name='xmlvalidationconfig',
            name='global_impuesto_trasladado',
            field=models.CharField(choices=[('ANY', 'Sin validar'), ('0', '0%'), ('16', '16%')], default='ANY', max_length=8),
        ),
        migrations.AddField(
            model_name='xmlvalidationconfig',
            name='global_nombre_receptor',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='xmlvalidationconfig',
            name='global_regimen_fiscal_receptor',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
    ]
