# Generated by Django 6.0.2 on 2026-03-11 21:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0021_xmlvalidationconfig_global_codigo_fiscal_receptor_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailOutboxLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('to_email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=240)),
                ('body', models.TextField(blank=True)),
                ('provider', models.CharField(default='smtp', max_length=40)),
                ('status', models.CharField(default='SENT', max_length=20)),
                ('error', models.TextField(blank=True)),
                ('compra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_logs', to='pagos.compra')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
    ]
