# Generated by Django 6.0.2 on 2026-03-11 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0022_emailoutboxlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=40, unique=True)),
                ('nombre', models.CharField(max_length=120)),
                ('scenario', models.CharField(blank=True, default='GENERAL', max_length=40)),
                ('subject_template', models.CharField(max_length=240)),
                ('body_template', models.TextField()),
                ('is_default', models.BooleanField(default=False)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.AddField(
            model_name='emailoutboxlog',
            name='template_code',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
    ]
