# Generated by Django 6.0.2 on 2026-03-12 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0024_productorcuentabancaria'),
    ]

    operations = [
        migrations.AddField(
            model_name='productorcuentabancaria',
            name='caratula_archivo',
            field=models.FileField(blank=True, upload_to='compras_documentos/%Y/%m/'),
        ),
    ]
