# Generated by Django 6.0.2 on 2026-03-12 20:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0025_productorcuentabancaria_caratula_archivo'),
    ]

    operations = [
        migrations.CreateModel(
            name='BeneficiaryValidationException',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('emisor_rfc', models.CharField(blank=True, default='', max_length=20)),
                ('emisor_nombre', models.CharField(blank=True, default='', max_length=200)),
                ('account_holder', models.CharField(max_length=200)),
                ('reason', models.CharField(blank=True, max_length=240)),
                ('active', models.BooleanField(default=True)),
                ('facturador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='beneficiary_exceptions', to='pagos.personafactura')),
                ('productor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='beneficiary_exceptions', to='pagos.productor')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
    ]
