# Generated by Django 6.0.2 on 2026-03-12 20:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0026_beneficiaryvalidationexception'),
    ]

    operations = [
        migrations.CreateModel(
            name='FacturadorCuentaBancaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('banco', models.CharField(blank=True, max_length=120)),
                ('titular', models.CharField(blank=True, max_length=200)),
                ('cuenta', models.CharField(max_length=80)),
                ('clabe', models.CharField(blank=True, max_length=30)),
                ('caratula_archivo', models.FileField(blank=True, upload_to='compras_documentos/%Y/%m/')),
                ('activa', models.BooleanField(default=True)),
                ('predeterminada', models.BooleanField(default=False)),
                ('facturador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cuentas_bancarias', to='pagos.personafactura')),
            ],
            options={
                'ordering': ['-predeterminada', 'banco', 'cuenta'],
            },
        ),
    ]
