# Generated by Django 6.0.2 on 2026-03-13 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0027_facturadorcuentabancaria'),
    ]

    operations = [
        migrations.AddField(
            model_name='compra',
            name='compra_pdf_validada',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='compra',
            name='compra_pdf_validada_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
