# Generated by Django 6.0.2 on 2026-03-13 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0028_compra_compra_pdf_validada_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productor',
            name='rfc',
            field=models.CharField(blank=True, db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='documentocompra',
            name='etapa',
            field=models.CharField(choices=[('compra_original', 'Compra original'), ('solicitud_factura', 'Solicitud Factura'), ('factura', 'Factura'), ('pago', 'Pago'), ('otro', 'Otro')], default='otro', max_length=30),
        ),
    ]
