# Generated by Django 6.0.2 on 2026-03-18 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0031_documentocompra_tipo_documento'),
    ]

    operations = [
        migrations.AddField(
            model_name='contador',
            name='emails_adicionales',
            field=models.TextField(blank=True, default=''),
        ),
    ]
