# Generated by Django 6.0.2 on 2026-03-23 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0032_contador_emails_adicionales'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compra',
            name='porcentaje_division',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True),
        ),
    ]
