# Generated by Django 6.0.2 on 2026-03-27 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0033_alter_compra_porcentaje_division'),
    ]

    operations = [
        migrations.AddField(
            model_name='compra',
            name='invoice_override_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='compra',
            name='invoice_override_authorized',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='compra',
            name='invoice_override_by',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='compra',
            name='invoice_override_reason',
            field=models.TextField(blank=True, default=''),
        ),
    ]
