from django.urls import path

from .api_views import api_compra_detail, api_queue_summary
from .views import (
    HomeView,
    anticipos_view,
    api_facturador_contacto_view,
    compra_create_view,
    division_delete_view,
    pago_delete_view,
    compra_delete_view,
    compra_edit_view,
    compra_flujo_view,
    compra_mapear_microsip_view,
    compra_validacion_factura_view,
    compras_archivadas_view,
    configuracion_validacion_xml_view,
    compras_operativas_view,
    contador_edit_view,
    contadores_catalogo_view,
    facturador_edit_view,
    facturadores_catalogo_view,
    import_anticipos_view,
    import_compras_view,
    readiness_queue_action_view,
    readiness_queue_view,
    productor_edit_view,
    productores_catalogo_view,
    registro_view,
)

urlpatterns = [
    path("", HomeView.as_view(), name="home"),
    path("registro/", registro_view, name="registro"),
    path("compras/", compras_operativas_view, name="compras_operativas"),
    path("compras/archivadas/", compras_archivadas_view, name="compras_archivadas"),
    path("import/compras/", import_compras_view, name="import_compras"),
    path("import/anticipos/", import_anticipos_view, name="import_anticipos"),
    path("queue/", readiness_queue_view, name="readiness_queue"),
    path("queue/<int:compra_id>/action/", readiness_queue_action_view, name="readiness_queue_action"),
    path("compras/nueva/", compra_create_view, name="compra_create"),
    path("compras/<int:compra_id>/flujo/", compra_flujo_view, name="compra_flujo"),
    path("compras/<int:compra_id>/mapear-microsip/", compra_mapear_microsip_view, name="compra_mapear_microsip"),
    path("compras/<int:compra_id>/validacion-factura/", compra_validacion_factura_view, name="compra_validacion_factura"),
    path("api/queue/summary/", api_queue_summary, name="api_queue_summary"),
    path("api/compras/<int:compra_id>/", api_compra_detail, name="api_compra_detail"),
    path("api/facturadores/<int:facturador_id>/contacto/", api_facturador_contacto_view, name="api_facturador_contacto"),
    path("compras/<int:compra_id>/editar/", compra_edit_view, name="compra_edit"),
    path("compras/<int:compra_id>/eliminar/", compra_delete_view, name="compra_delete"),
    path("compras/<int:compra_id>/eliminar-division/", division_delete_view, name="division_delete"),
    path("pagos/<int:pago_id>/eliminar/", pago_delete_view, name="pago_delete"),
    path("anticipos/", anticipos_view, name="anticipos"),
    path("productores/", productores_catalogo_view, name="productores_catalogo"),
    path("productores/<int:productor_id>/editar/", productor_edit_view, name="productor_edit"),
    path("contadores/", contadores_catalogo_view, name="contadores_catalogo"),
    path("contadores/<int:contador_id>/editar/", contador_edit_view, name="contador_edit"),
    path("facturadores/", facturadores_catalogo_view, name="facturadores_catalogo"),
    path("facturadores/<int:facturador_id>/editar/", facturador_edit_view, name="facturador_edit"),
    path("config/xml-validacion/", configuracion_validacion_xml_view, name="config_validacion_xml"),
]
